export const skins = {
  default: {
    name: 'Classic Snake',
    description: 'The classic green snake',
    color: '#4a8f4a',
    borderColor: '#2e5a2e',
    headImage: '/images/player.webp',
    requiredScore: 0,
  },
  ghost: {
    name: 'Ghost Snake',
    description: 'A spooky transparent snake',
    color: 'rgba(255, 255, 255, 0.3)',
    borderColor: 'rgba(255, 255, 255, 0.5)',
    headImage: '/images/player.webp',
    requiredScore: 50,
    glowEffect: '0 0 10px rgba(255, 255, 255, 0.5)',
  },
  blue: {
    name: 'Blue Snake',
    description: 'A cool blue snake',
    bodyImage: '/images/skins/blue_skin.svg',
    borderColor: '#003366',
    headImage: '/images/player.webp',
    requiredScore: 100,
  },
  blueV2: {
    name: 'Blue Snake V2',
    description: 'An alternative blue snake design',
    bodyImage: '/images/skins/blue_skin_v2.svg',
    borderColor: '#003366',
    headImage: '/images/player.webp',
    requiredScore: 150,
  },
  blueV3: {
    name: 'Blue Snake V3',
    description: 'The ultimate blue snake',
    bodyImage: '/images/skins/blue_skin_v3.svg',
    borderColor: '#003366',
    headImage: '/images/player.webp',
    requiredScore: 200,
  },
  green: {
    name: 'Green Snake',
    description: 'A vibrant green snake',
    bodyImage: '/images/skins/green_skin.svg',
    borderColor: '#2e5a2e',
    headImage: '/images/player.webp',
    requiredScore: 250,
  },
  greenV2: {
    name: 'Green Snake V2',
    description: 'An alternative green snake design',
    bodyImage: '/images/skins/green_skin_v2.svg',
    borderColor: '#2e5a2e',
    headImage: '/images/player.webp',
    requiredScore: 300,
  },
  greenV3: {
    name: 'Green Snake V3',
    description: 'The ultimate green snake',
    bodyImage: '/images/skins/green_skin_v3.svg',
    borderColor: '#2e5a2e',
    headImage: '/images/player.webp',
    requiredScore: 350,
  },
  orange: {
    name: 'Orange Snake',
    description: 'A fiery orange snake',
    bodyImage: '/images/skins/orange_skin.svg',
    borderColor: '#cc3300',
    headImage: '/images/player.webp',
    requiredScore: 400,
  },
  orangeV2: {
    name: 'Orange Snake V2',
    description: 'An alternative orange snake design',
    bodyImage: '/images/skins/orange_skin_v2.svg',
    borderColor: '#cc3300',
    headImage: '/images/player.webp',
    requiredScore: 450,
  },
  orangeV3: {
    name: 'Orange Snake V3',
    description: 'The ultimate orange snake',
    bodyImage: '/images/skins/orange_skin_v3.svg',
    borderColor: '#cc3300',
    headImage: '/images/player.webp',
    requiredScore: 500,
  },
};
