export const skins = {
  default: {
    name: 'Classic Snake',
    description: 'The classic green snake',
    color: '#4a8f4a',
    borderColor: '#2e5a2e',
    headImage: '/images/player.webp',
    requiredScore: 0,
  },
  fire: {
    name: 'Fire Snake',
    description: 'A blazing hot snake',
    color: 'linear-gradient(45deg, #ff4d4d, #ff9933)',
    borderColor: '#cc3300',
    headImage: '/images/player.webp',
    requiredScore: 50,
  },
  ice: {
    name: 'Ice Snake',
    description: 'A freezing cold snake',
    color: 'linear-gradient(45deg, #00ccff, #0066cc)',
    borderColor: '#003366',
    headImage: '/images/player.webp',
    requiredScore: 100,
  },
  ghost: {
    name: 'Ghost Snake',
    description: 'A spooky transparent snake',
    color: 'rgba(255, 255, 255, 0.3)',
    borderColor: 'rgba(255, 255, 255, 0.5)',
    headImage: '/images/player.webp',
    requiredScore: 150,
    glowEffect: '0 0 10px rgba(255, 255, 255, 0.5)',
  },
  rainbow: {
    name: 'Rainbow Snake',
    description: 'A magical rainbow snake',
    color: 'linear-gradient(45deg, #ff0000, #ff7f00, #ffff00, #00ff00, #0000ff, #4b0082, #8b00ff)',
    borderColor: '#ff0000',
    headImage: '/images/player.webp',
    requiredScore: 200,
    animation: 'rainbow 2s linear infinite',
  },
  metal: {
    name: 'Metal Snake',
    description: 'A sleek metallic snake',
    color: 'linear-gradient(180deg, #c0c0c0, #808080)',
    borderColor: '#404040',
    headImage: '/images/player.webp',
    requiredScore: 250,
    metalEffect: true,
  },
  pixel: {
    name: 'Pixel Snake',
    description: 'A retro pixelated snake',
    color: '#32cd32',
    borderColor: '#228b22',
    headImage: '/images/player.webp',
    requiredScore: 300,
    pixelEffect: true,
  },
  galaxy: {
    name: 'Galaxy Snake',
    description: 'A cosmic snake from outer space',
    color: 'linear-gradient(45deg, #000033, #660066)',
    borderColor: '#9933ff',
    headImage: '/images/player.webp',
    requiredScore: 400,
    starEffect: true,
  }
};
